//! Two build-time jobs: the Windows icon, and the translation catalogs.
//!
//! Windows takes an executable's icon from a resource compiled into the
//! binary, not from a file beside it, so this is the only way Explorer, the
//! taskbar and Alt-Tab get anything other than a blank default. Linux has no
//! equivalent: there the desktop entry names the icon, and
//! `install-desktop-linux.sh` puts both where the desktop can
//! find them.
//!
//! The catalogs are the other half of what `src/i18n.rs` describes: every
//! `po/*.po` named in `po/LINGUAS` is parsed here and written out as Rust
//! source, which that module includes. Nothing is installed and nothing is
//! read from disk at runtime, for the reason every other asset in this project
//! is compiled in - there is no `share/` directory on Windows or macOS, and
//! the portable zip has to work unpacked anywhere.

use std::fmt::Write as _;
use std::path::Path;

/// The `Plural-Forms` parser, shared with the running application rather than
/// written twice. See the file's own comment: `build.rs` renders a rule into
/// Rust, the runtime evaluates one directly, and the two must not be able to
/// disagree about what a rule means.
mod plural_rule {
    include!("src/plural_rule.rs");
}

fn main() {
    #[cfg(target_os = "windows")]
    {
        println!("cargo:rerun-if-changed=data/branding/tineplayer.ico");
        let mut resource = winresource::WindowsResource::new();
        resource.set_icon("data/branding/tineplayer.ico");
        if let Err(e) = resource.compile() {
            // Not fatal: a binary without an icon still runs, and failing the
            // build over decoration would be worse than the missing icon.
            println!("cargo:warning=Could not embed the icon: {e}");
        }
    }

    println!("cargo:rerun-if-changed=src/plural_rule.rs");
    build_catalogs();
}

/// Reads `po/LINGUAS`, parses every catalog it names, and writes
/// `$OUT_DIR/catalogs.rs`.
///
/// **Failures here are fatal, deliberately.** A catalog that will not parse,
/// or a plural rule that makes no sense, is a mistake in this repository, and
/// the alternative to stopping is an application that quietly comes up in
/// English for one language until somebody who reads that language says so.
///
/// This is the opposite of how a *user's* config file is treated, which falls
/// back to defaults and says so on screen. That one is somebody's own machine
/// and has to keep working. This one is ours, and has a build to fail.
fn build_catalogs() {
    println!("cargo:rerun-if-changed=po");

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs from po/*.po. Do not edit.\n\n");

    let mut catalogs = String::new();

    for (index, code) in linguas().iter().enumerate() {
        let path = Path::new("po").join(format!("{code}.po"));
        println!("cargo:rerun-if-changed={}", path.display());

        let catalog = polib::po_file::parse(&path)
            .unwrap_or_else(|e| panic!("po/{code}.po could not be read: {e}"));

        let rules = &catalog.metadata.plural_rules;
        let rule = plural_rule::parse(&rules.expr)
            .unwrap_or_else(|e| panic!("po/{code}.po has an unusable Plural-Forms rule: {e}"));

        // Singular and plural messages are kept in separate tables rather than
        // in one with an optional second column. The `tr!` lookup is much the
        // commoner of the two and has no business paying for a slice
        // indirection on every string in the interface.
        let mut singular: Vec<(String, String)> = Vec::new();
        let mut plural: Vec<(String, Vec<String>)> = Vec::new();

        for message in catalog.messages() {
            // Fuzzy is gettext's word for "a merge or a machine guessed at
            // this and no human has confirmed it". Skipping them is what every
            // gettext runtime does, and it means the msgid shows through
            // instead: English, but English somebody wrote.
            if message.is_fuzzy() || !message.is_translated() {
                continue;
            }

            let key = match message.msgctxt() {
                // The separator gettext itself puts between a context and its
                // message, so that a context and a message cannot be confused
                // for one another however they are spelled.
                Some(context) => format!("{context}\u{4}{}", message.msgid()),
                None => message.msgid().to_string(),
            };

            match message.is_plural() {
                true => {
                    let forms = message
                        .msgstr_plural()
                        .unwrap_or_else(|e| panic!("po/{code}.po: \"{key}\": {e}"))
                        .clone();
                    if forms.len() != rules.nplurals {
                        panic!(
                            "po/{code}.po: \"{key}\" has {} plural forms but the header declares \
                             nplurals={}",
                            forms.len(),
                            rules.nplurals
                        );
                    }
                    plural.push((key, forms));
                }
                false => {
                    let translated = message
                        .msgstr()
                        .unwrap_or_else(|e| panic!("po/{code}.po: \"{key}\": {e}"))
                        .to_string();
                    singular.push((key, translated));
                }
            }
        }

        // Sorted here so the lookup can binary search rather than scan. Done at
        // build time because it costs nothing here, and would otherwise be a
        // startup cost paid on every run of the application.
        singular.sort_by(|a, b| a.0.cmp(&b.0));
        plural.sort_by(|a, b| a.0.cmp(&b.0));

        // Redundant brackets are allowed rather than avoided: the renderer
        // brackets every node defensively, because a rule's precedence has to
        // survive being nested inside another one, and teaching it which
        // brackets are unnecessary would be a second precedence implementation
        // to get wrong. Both lints are named because rustc and clippy each
        // have their own, and CI runs both.
        writeln!(
            generated,
            "/// `{}` - the Plural-Forms rule from po/{code}.po.\n\
             #[allow(unused_parens, clippy::double_parens)]\n\
             fn plural_index_{index}(n: u64) -> usize {{\n    ({}) as usize\n}}\n",
            rules.expr.trim(),
            rule.as_value(),
        )
        .expect("writing to a String cannot fail");

        writeln!(
            generated,
            "static SINGULAR_{index}: &[(&str, &str)] = &[{}];",
            singular
                .iter()
                .map(|(key, value)| format!("({}, {})", quote(key), quote(value)))
                .collect::<Vec<_>>()
                .join(", ")
        )
        .expect("writing to a String cannot fail");

        writeln!(
            generated,
            "static PLURAL_{index}: &[(&str, &[&str])] = &[{}];\n",
            plural
                .iter()
                .map(|(key, forms)| {
                    let forms = forms
                        .iter()
                        .map(|f| quote(f))
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("({}, &[{forms}])", quote(key))
                })
                .collect::<Vec<_>>()
                .join(", ")
        )
        .expect("writing to a String cannot fail");

        writeln!(
            catalogs,
            "    Catalog {{ code: {}, singular: SINGULAR_{index}, plural: PLURAL_{index}, \
             nplurals: {}, plural_index: plural_index_{index} }},",
            quote(code),
            rules.nplurals,
        )
        .expect("writing to a String cannot fail");
    }

    writeln!(
        generated,
        "/// Every translation compiled into this binary, in the order \
         po/LINGUAS names them.\npub static CATALOGS: &[Catalog] = &[\n{catalogs}];"
    )
    .expect("writing to a String cannot fail");

    let out = Path::new(&std::env::var("OUT_DIR").expect("cargo always sets OUT_DIR"))
        .join("catalogs.rs");
    std::fs::write(&out, generated)
        .unwrap_or_else(|e| panic!("could not write {}: {e}", out.display()));
}

/// The locales to compile in, from `po/LINGUAS`.
///
/// A list rather than "every `.po` in the folder", which is gettext's own
/// convention and also the safer of the two: a half-finished catalog somebody
/// dropped in to look at should not ship merely by existing. Blank lines and
/// `#` comments are ignored, and several codes may share a line, which is how
/// these files are usually written.
fn linguas() -> Vec<String> {
    let path = Path::new("po").join("LINGUAS");
    println!("cargo:rerun-if-changed={}", path.display());

    let Ok(text) = std::fs::read_to_string(&path) else {
        // No catalogs at all is a legitimate state. It is what a checkout looks
        // like before the first translation arrives, and English never has one
        // of its own - it is the language the source is written in.
        return Vec::new();
    };

    text.lines()
        .map(|line| line.split('#').next().unwrap_or_default())
        .flat_map(str::split_whitespace)
        .map(str::to_string)
        .collect()
}

/// A Rust string literal holding exactly `text`.
///
/// Hand-rolled rather than `{:?}`, which is close but is not a promise: its
/// output is meant for a person reading a debug dump, and how it escapes
/// non-ASCII has changed between releases. What goes into generated source has
/// to be exactly right for every catalog in every script, so the escaping is
/// spelled out here rather than borrowed.
fn quote(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    out.push('"');
    for character in text.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            // Everything else goes through as itself, including the U+0004
            // context separator and every non-Latin script: the generated file
            // is UTF-8 and so is Rust source.
            _ => out.push(character),
        }
    }
    out.push('"');
    out
}
